apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: omnimap

resources:
  - namespace.yaml
  - configmap.yaml
  - secrets.yaml
  - omnimap-back.yaml
  - omnimap-front.yaml
  - omnimap-sync.yaml
  - llm-gateway.yaml
  - ingress.yaml

commonLabels:
  app.kubernetes.io/part-of: omnimap-platform
