apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: omnimap

resources:
  - ../../base

patches:
  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 3
    target:
      kind: Deployment
      name: omnimap-back

  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 3
    target:
      kind: Deployment
      name: llm-gateway

configMapGenerator:
  - name: omnimap-config
    behavior: merge
    literals:
      - DEBUG=false
      - LOG_LEVEL=INFO
      - ENVIRONMENT=production
